
# Spring related settings
server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/irctc?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa: 
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    #open-in-view: false
    #properties:
     # hibernate.format_sql: true
# logging level
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.ust: DEBUG
    #org.hibernate.SQL: info
    #org.hibernate.type.descriptor.sql: trace
